# Generated by Django 4.2.16 on 2025-04-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_transaction_status_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
