# Generated by Django 4.2.7 on 2024-12-29 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0003_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
